name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.2.0-beta.11
repository: https://github.com/zino-app/graphql-flutter/tree/main/packages/graphql
issue_tracker: https://github.com/zino-hofmann/graphql-flutter/issues

dependencies:
  meta: 
  path: 
  gql: 
  gql_exec: 
  gql_link: 
  gql_http_link: 
  gql_transform_link: 
  gql_error_link: 
  gql_dedupe_link: 
  hive: 
  normalize: 
  http: 
  collection: 
  web_socket_channel:
  stream_channel: 
  rxdart: 
  uuid: 

dev_dependencies:
  async: 
  mockito:
  test: 
  coverage: 
  http_parser: 
  lints: 

environment:
  sdk: '>=3.0.0 <4.0.0'
