name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.2.0-beta.7
repository: https://github.com/zino-app/graphql-flutter/tree/main/packages/graphql_flutter
issue_tracker: https://github.com/zino-hofmann/graphql-flutter/issues

# just for dev work
# publish_to: 'none'

dependencies:
  graphql: ^5.2.0-beta.8
  gql_exec:
  flutter:
    sdk: flutter
  meta: 
  path_provider: 
  path: 
  connectivity_plus: 
  hive: 
  plugin_platform_interface: 
  flutter_hooks: '>=0.18.2 <0.21.0'

dev_dependencies:
  pedantic: 
  mockito: 
  flutter_test:
    sdk: flutter
  http: 
  test: 

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.11.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
